const productData = [
    {
        id:1,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/M6cPRbN/pic1.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:2,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/47nBr2f/pic2.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:3,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/H7Cb80m/pic3.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:4,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/kQq66KZ/pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:5,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/M6cPRbN/pic1.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:6,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/47nBr2f/pic2.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:7,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/H7Cb80m/pic3.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:8,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/kQq66KZ/pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:9,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/M6cPRbN/pic1.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:10,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/47nBr2f/pic2.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:11,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/H7Cb80m/pic3.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
    {
        id:12,
        name:"Bán nhà Phố Trạm 35m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "https://i.ibb.co/kQq66KZ/pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '35m2' ,
        bedroom: '3',
        bathroom: '2',
    },
   
];
export default productData;